[package]
name = "markman"
version = "0.1.0"
edition = "2021"

[lib]
name = "markman"
path = "src/lib.rs"

[[bin]]
name = "markman"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
clap = { version = "4", features = ["derive"] }
tiny_http = "0.12"
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tempfile = "3.8"
