[package]
name = "markman"
version = "0.0.1"
edition = "2021"

[lib]
name = "markman"
path = "src/lib.rs"

[[bin]]
name = "markman"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
clap = { version = "4", features = ["derive"] }
tiny_http = "0.12"
urlencoding = "2"
html-escape = "0.2"

[dev-dependencies]
tempfile = "3"
