files = [
    "src/encoder.zig",
]
success = true
verify_output = "Build Summary: 3/3 steps succeeded\ninstall cached\n+- install qoizig cached\n   +- compile exe qoizig Debug native cached 32ms MaxRSS:34M"
